/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/small-and-large-intestine/scene.gltf -o src/components/SmallAndLargeIntestine.jsx -r public 
Author: antonia.sundberg (https://sketchfab.com/antonia.sundberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-and-large-intestine-8a1ca8e3ca224cdeb9264674416bde38
Title: Small and large intestine
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function SmallAndLargeIntestine(props) {
  // GLTF Hook
  const { nodes, materials } = useGLTF(
    '/models/small-and-large-intestine/scene.gltf'
  );

  //--------------------- Render -----------------------------
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.037}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[15.286, 3.827, -1.997]} scale={0.1}>
            <mesh
              geometry={nodes.Tjocktarm_Default_Material_0.geometry}
              material={materials.Default_Material}
            />
            <mesh
              geometry={nodes.Tjocktarm_Default_Material_0_1.geometry}
              material={materials.Default_Material}
            />
          </group>
          <mesh
            geometry={nodes.Tunntarm_Default_Material_0.geometry}
            material={materials.Default_Material_0}
            position={[14.166, 10.696, 1.169]}
            scale={0.1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/small-and-large-intestine/scene.gltf');
